export const LOGIN_USERS="LOGIN_USERS"
export const REGISTER_USERS="REGISTER_USERS"

export const GET_USERS="GET_USERS"
export const GET_ALL_PROF="GET_ALL_PROF"

export const GET_ADMIN="GET_ADMIN"
export const GET_USER="GET_USER"
export const UPDATE_USER="UPDATE_USER"
export const UPDATE_ADMIN="UPDATE_ADMIN"
export const GET_CLASSES="GET_CLASSES"
export const CREATE_CLASSES="CREATE_CLASSES"
export const DELETE_CLASSES="DELETE_CLASSES"

export const GET_GROUPES="GET_GROUPES"
export const CREATE_GROUPE="CREATE_GROUPE"
export const DELETE_GROUPE="DELETE_GROUPE"

export const GET_LEVEL="GET_LEVEL"
export const POST_STUDENT="POST_STUDENT"
export const POST_PROF="POST_PROF"
export const GET_GROUE_CLASS="GET_GROUE_CLASS"
export const DELETE_GROUPE_CLASS="DELETE_GROUPE_CLASS"
export const ALL_CLASSES="ALL_CLASSES"